#include "../stub.h"

DEF(0x00006538,hPtpMgr)
DEF(0x00016B60,DPData)
DEF(0x00005884,LensID)
DEF(0x00001CD4,is_release_permitted)
DEF(0xFF821844,able_to_release)
DEF(0xFF8219B4,permit_or_inhibit_release)
DEF(0x00019638,VramAddress)
DEF(0x0000F490,VramInfo)

DEF(0x00001CE8,shutter_lock) // Just guessing

/* Investigations */
DEF(0x00018850,DPData_at_start)
DEF(0x00018F88,DPData_2)
DEF(0x00010000,MIN_ADDR)
DEF(0x0001FFFF,MAX_ADDR)
/* TODO: Does not belong here */
